package dena.api.common.interop.context;

import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import dena.api.common.model.DN00IsDENAModelObject;
import dena.api.common.model.oids.interop.DN00InteropIDs.DN00InteropComponent;
import dena.api.common.model.oids.interop.DN00InteropOIDs.DN00MessageCorrelationOID;
import r01f.debug.Debuggable;
import r01f.objectstreamer.annotations.MarshallField;
import r01f.util.types.Strings;
import r01f.util.types.collections.CollectionUtils;

/**
 * Data about the interop message 
 */
public record DN00InteropMessageData(// The type of the message (ie: SYNC_META_DATA_FROM_CLIENT_INSTALLMENT_TO_CORE, SYNC_META_DATA_FROM_ADMIN_TO_CORE, etc)
									 @MarshallField(as="type")
    								 DN00InteropMessageType messageType,
    								 // An OID generated by the component that FIRST created the message (ie the [client installment] or [admin])
    								 // and that is used to correlate all the messages interchanged between the components to process a given request
    								 @MarshallField(as="correlationId") 
    								 DN00MessageCorrelationOID messageCorrelationId,
    								 // Every time the message passes through a dena component a DN00InteropRouteDataItem(itemId,timestamp) is added to this collection
									 // this info is used for debugging purposes 
									 @MarshallField(as="interopRouteData")
    								 List<DN00IteropRouteDataItem> interopRouteData) 
	implements Debuggable,
			   DN00IsDENAModelObject {
/////////////////////////////////////////////////////////////////////////////////////////
//	CONSTRUCTORS
/////////////////////////////////////////////////////////////////////////////////////////
	public DN00InteropMessageData(final DN00InteropMessageType messageType,
								  final DN00MessageCorrelationOID messageCorrelationId,
								  final List<DN00IteropRouteDataItem> interopRouteData) {
		this.messageType = messageType;
		this.messageCorrelationId = messageCorrelationId;
		this.interopRouteData = CollectionUtils.hasData(interopRouteData) 
									? new LinkedList<>(interopRouteData.stream()
													   // Remove duplicates by componentId
													   // there should NOT exist two [interop route data item]
													   // with the same componentId but if it happens, we keep the first occurrence
													   .collect(Collectors.toMap(// key and value mapping functions
													  						     DN00IteropRouteDataItem::componentId,Function.identity(),
													  					         // AFTER processing all the stream elements, 
													  						     // if the mapped KEYS contain duplicates, 
													  					         // the VALUE mapping function is applied 
													  					         // to each equal (duplicate) element, 
													  						     // and the results are merged using merging function.
													  					         (existing,replacement) -> existing)) // Keep the first occurrence on duplicate id
													   .values())
									: new LinkedList<>();
	}
	public DN00InteropMessageData(final DN00InteropMessageType messageType,
								  final DN00MessageCorrelationOID messageCorrelationId,
								  final DN00IteropRouteDataItem... routeItems) {
		this(messageType,
			 messageCorrelationId,
			 CollectionUtils.hasData(routeItems) ? List.of(routeItems) : new LinkedList<>());
	}
	public DN00InteropMessageData(final DN00InteropMessageType messageType,
								  final DN00MessageCorrelationOID messageCorrelationId) {
		this(messageType,
			 messageCorrelationId,
			 new LinkedList<>());
	}
	public DN00InteropMessageData(final DN00InteropMessageType messageType) {
		this(messageType,
			 null);
	}
	public DN00InteropMessageData(final DN00MessageCorrelationOID messageCorrelationId) {
		this(null,
			 messageCorrelationId);
	}
	public DN00InteropMessageData(final List<DN00IteropRouteDataItem> interopRouteData) {
		this(null,
			 (DN00MessageCorrelationOID)null,
			 interopRouteData != null ? interopRouteData : new LinkedList<>());
	}
	public DN00InteropMessageData(final DN00IteropRouteDataItem... interopRouteData) {
		this(null,
			 null,
			 CollectionUtils.hasData(interopRouteData) ? List.of(interopRouteData) : new LinkedList<>());
	}
/////////////////////////////////////////////////////////////////////////////////////////
//	
/////////////////////////////////////////////////////////////////////////////////////////	
	public static DN00InteropMessageData unmodifiableCopyOf(final DN00InteropMessageData data) {
		return new DN00InteropMessageData(data.messageType(),
										  data.messageCorrelationId(),
										  List.copyOf(data.interopRouteData()));	// BEWARE: convert to immutable list copy of the original!!
	}
	public static DN00InteropMessageData modifiableCopyOf(final DN00InteropMessageData data) {
		return new DN00InteropMessageData(data.messageType(),
										  data.messageCorrelationId(),
										  new LinkedList<>(data.interopRouteData()));
	}
/////////////////////////////////////////////////////////////////////////////////////////
//	
/////////////////////////////////////////////////////////////////////////////////////////
    public boolean containsRouteItem(final DN00InteropComponent componentId) {
		return this.interopRouteData != null
			&& this.interopRouteData.stream()
									.anyMatch(item -> item.getComponentId().is(componentId));
    }
/////////////////////////////////////////////////////////////////////////////////////////
//	GETTERS
/////////////////////////////////////////////////////////////////////////////////////////    
    public DN00InteropMessageType getMessageType() {
    	return this.messageType();
    }
    public boolean isMessageOfType(final DN00InteropMessageType type) {
    	return this.messageType != null
			&& this.messageType.equals(type);
    }
    public DN00MessageCorrelationOID getMessageCorrelationId() {
		return this.messageCorrelationId();
	}
    public DN00InteropFlowDirection flowDirection() {
    	return this.messageType != null ? this.messageType.getFlowDirection()
									    : null;
    }
    public DN00InteropFlowDirection getFlowDirection() {
		return this.flowDirection();
	}
    public boolean isMessageWithDirection(final DN00InteropFlowDirection flowDirection) {
		return this.flowDirection() != null
			&& this.flowDirection().is(flowDirection);
    }
    public DN00InteropMessageParty originParty() {
		return this.messageType != null ? this.messageType.getOriginParty()
									    : null;
	}
    public DN00InteropMessageParty getOriginParty() {
		return this.originParty();
	}
	public DN00InteropMessageParty destinationParty() {
		return this.messageType != null ? this.messageType.getDestinationParty()
									    : null;
	}
	public DN00InteropMessageParty getDestinationParty() {
		return this.destinationParty();
	}
	public Collection<DN00IteropRouteDataItem> getInteropRouteData() {
		return this.interopRouteData();
	}
    public Stream<DN00IteropRouteDataItem> getRouteDataStreamSortedByTimeStampOldestFirst() {
    	return this.interopRouteData != null
					? this.interopRouteData.stream()
									       .sorted((i1,i2) -> i1.getTimeStamp().compareTo(i2.getTimeStamp()))
					: null;
    }
    public Collection<DN00IteropRouteDataItem> getRouteDataSortedByTimeStamp() {
    	Stream<DN00IteropRouteDataItem> sorted = this.getRouteDataStreamSortedByTimeStampOldestFirst();
    	return sorted != null ? sorted.toList()
						  	  : null;
    }
    /**
     * Returns the first route item (the one with the oldest timestamp)
     * @return
     */
    public DN00IteropRouteDataItem getOriginRouteItem() {
    	Stream<DN00IteropRouteDataItem> sorted = this.getRouteDataStreamSortedByTimeStampOldestFirst();
    	return sorted != null ? sorted.findFirst()
							   		  .orElse(null)
							  : null;
	}
    /**
     * Returns the last route item (the one with the newest timestamp)
     * @return
     */
    public DN00IteropRouteDataItem getLastRouteItem() {
		Stream<DN00IteropRouteDataItem> sorted = this.getRouteDataStreamSortedByTimeStampOldestFirst();
		return sorted != null ? sorted.reduce((first,second) -> second)
							   		  .orElse(null)
							  : null;
    }
/////////////////////////////////////////////////////////////////////////////////////////
//	DEBUG
/////////////////////////////////////////////////////////////////////////////////////////    
	@Override
	public CharSequence debugInfo() {
		return Strings.customized("type={} ({}) / correlationId={}",
							  	  this.messageType,this.flowDirection(),
							  	  this.messageCorrelationId);
	}
}
