package dena.api.common.model.securitycontext.user;


import dena.api.common.model.refs.person.DN00PersonRef;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import r01f.aspects.interfaces.dirtytrack.ConvertToDirtyStateTrackable;
import r01f.model.security.user.User;
import r01f.model.security.user.UserBase;
import r01f.objectstreamer.annotations.MarshallField;
import r01f.objectstreamer.annotations.MarshallField.MarshallFieldAsXml;
import r01f.objectstreamer.annotations.MarshallType;
import r01f.securitycontext.SecurityIDS.IsIdentityBrokerObjectID;
import r01f.util.comparable.ComparableObjectUtils;
import r01f.validation.ObjectValidationResult;
import r01f.validation.SelfValidates;


/*********************************
 * What is a PersonUser?
 * ############################
	The concept of a PersonUser represents a technical security user created and managed within an Identity Broker (such as Keycloak or WSO2 Identity Server).

	Its primary purpose is to act as a unified identity bridge. When your system allows authentication through various external identity providers (such as Google, Giltza/Izenpe, etc.), the Identity Broker does not directly expose the raw data from those providers to the entire core application. Instead, it centralizes authentication and generates this lightweight, intermediate PersonUser object, which stores only the minimal and necessary information required to unambiguously identify and link the user.

	Structure and Minimal Data of a PersonUser
	#########################################

To fulfill its bridging role without duplicating unnecessary business data, a PersonUser consists exclusively of three key identifiers:

	1. The Identity Broker OID
	-----------------------------
		What it is: The universal unique identifier (UUID) internally generated by the Identity Broker itself (for example, the internal user_id assigned by Keycloak).

		Function: It is used to manage the technical security session, access tokens, and refresh tokens within the security architecture.

	2. The Original Security Provider ID
	-------------------------------------
		What it is: The unique identifier returned by the specific external provider that the user physically used to authenticate.

		Example with Giltza: The user's DNI/NIE from their digital certificate.

		Example with Google: The user's email address or Google Account ID.

		Function: It tracks the external source or "window" the user came from, validating their original authenticity every time they log in.

	3. The PersonOID at Person REF (The Core System Link)
	----------------------------------------
		What it is: The unique object identifier (person_oid) that points directly to the actual record of the individual in the operational or business database.

		Function: This is the key to the integration, decoupling the security layer from the business layer. Thanks to the PersonOID, once the authentication flow completes successfully, the application core knows exactly which physical entity or database profile that technical user corresponds to, allowing it to load their business roles, permissions, and operational data.

	The Identity Flow at a Glance
	#################################
	When a user logs in, the PersonUser object orchestrates the identity resolution as follows:

	[1] The user authenticates via Giltza using their DNI.

	[2] The Identity Broker intercepts this DNI, locates or provisions the corresponding technical PersonUser, and attaches its own session OID.

	[3] The Identity Broker resolves which internal PersonOID in the business database is mapped to this security profile.

	The application receives a unified token and seamlessly translates the technical security user into "Person X" within your database core.
 */
@MarshallType(as="personUser")
@ConvertToDirtyStateTrackable
@Accessors(prefix="_")
public class DN00DENAPersonUser
	 extends UserBase<DN00DENAPersonUser>
  implements SelfValidates<DN00DENAPersonUser>,
			 DN00IsDENAUser {

	    private static final long serialVersionUID = 2327019403550008421L;
/////////////////////////////////////////////////////////////////////////////////////////
//	FIELDS
/////////////////////////////////////////////////////////////////////////////////////////

	 @MarshallField(as="personRef",  // This constains the oid of the Person at DB
		             whenXml=@MarshallFieldAsXml(attr=true))
	 @Getter @Setter private DN00PersonRef _personRef;
	/**
	 *
	 */
	@MarshallField(as="personUserId",// // This constains the id of the PersonUser at Keycloack
				   whenXml=@MarshallFieldAsXml(attr=true))
	@Getter  private DN00DENAPersonUserID _personUserId;

	/**
	 * Something to display about the user *
	 */
    @MarshallField(as="givenName")
    @Getter @Setter private String _firstName;

    // The family name of the user.
    @MarshallField(as="familyName")
    @Getter @Setter private String _lastName;
/////////////////////////////////////////////////////////////////////////////////////////
//  CONSTRUCTOR
/////////////////////////////////////////////////////////////////////////////////////////
	public DN00DENAPersonUser() {
		super();
	}
/////////////////////////////////////////////////////////////////////////////////////////
//	UPDATE
/////////////////////////////////////////////////////////////////////////////////////////
	@Override
	public <U extends User> boolean updateFrom(final U other) {
		if (other == null) return false;
		if (other instanceof DN00DENAPersonUser) {
			return !this.isSameObject((DN00DENAPersonUser) other);
		}
		return true;
	}
/////////////////////////////////////////////////////////////////////////////////////////
//  SET IDENTITY BROKER ID
/////////////////////////////////////////////////////////////////////////////////////////
	public void setPersonUserId(final IsIdentityBrokerObjectID id) {
		_personUserId  = DN00DENAPersonUserID.from(id);
	}

/////////////////////////////////////////////////////////////////////////////////////////
//  VALIDATION
/////////////////////////////////////////////////////////////////////////////////////////
	@Override
	public ObjectValidationResult<DN00DENAPersonUser> validate() {
		return DN00DENAUserValidator.<DN00DENAPersonUser>createUserValidator()
									.validate(this);
	}
/////////////////////////////////////////////////////////////////////////////////////////
//
/////////////////////////////////////////////////////////////////////////////////////////
	@Override
	public boolean isSameObject(final DN00DENAPersonUser  other) {
		return  super.isSameObject(other)
				&&
				ComparableObjectUtils.compare(_personUserId.getId().toUpperCase(),
						other.getPersonUserId().getId().toUpperCase())
				&&
				ComparableObjectUtils.compare(_firstName,other.getFirstName())
				&&
				ComparableObjectUtils.compare(_lastName,other.getLastName())
				&&
				ComparableObjectUtils.compare(_personRef.getOid(),other.getPersonRef().getOid());
	}
/////////////////////////////////////////////////////////////////////////////////////////
//  MOCK
/////////////////////////////////////////////////////////////////////////////////////////	
	public static DN00DENAPersonUser buildMockForByPass() {
	    DN00DENAPersonUser bypassUser = new DN00DENAPersonUser();
        bypassUser.setFirstName("bypass");
        bypassUser.setLastName("bypass");
        bypassUser.setPersonUserId(DN00DENAPersonUserID.from("bypass"));
        return bypassUser;
	}
}
