<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>dena.api.common</groupId>
		<artifactId>denaCommonAPI</artifactId>
		<version>${revision}</version>
	</parent>

	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>denaCommonAPIModelClasses</name>
	<artifactId>denaCommonAPIModelClasses</artifactId>
	<packaging>jar</packaging>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!--  R01F: Fabric Base Model Classes          -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base</groupId>
			<artifactId>r01fModelClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<dependency>
			<groupId>r01.fabric.base.locale</groupId>
			<artifactId>r01fLocaleClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<!-- ///////////////////////////////////////// -->
		<!-- R01: Security Model                       -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.security.api</groupId>
			<artifactId>r01fSecurityModelClasses</artifactId>
			<version>${r01f.security.version}</version>
		</dependency>
		
		<!-- ///////////////////////////////////////// -->
		<!--  DENA: common                             -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>dena.api.common</groupId>
			<artifactId>denaCommonClasses</artifactId>
			<version>${revision}</version>
		</dependency>
    </dependencies>
</project>