<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>dena.api.common</groupId>
		<artifactId>denaCommonAPI</artifactId>
		<version>${revision}</version>
	</parent>

	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>denaCommonAPIClasses</name>
	<artifactId>denaCommonAPIClasses</artifactId>
	<packaging>jar</packaging>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!-- R01F: Security Model                      -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.security.api</groupId>
			<artifactId>r01fSecurityModelClasses</artifactId>
			<version>${r01f.security.version}</version>
		</dependency>
		<!-- ///////////////////////////////////////// -->
		<!-- R01F: Business Services                   -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.businessservices</groupId>
			<artifactId>r01fBusinessServicesClasses</artifactId>
			<version>${r01f.businessservices.version}</version>
		</dependency>
		
		<!-- ///////////////////////////////////////// -->
		<!--  DENA Common: Model                       -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>dena.api.common</groupId>
			<artifactId>denaCommonAPIModelClasses</artifactId>
			<version>${revision}</version>
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!--  DENA Common: Classes                     -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>dena.api.common</groupId>
			<artifactId>denaCommonClasses</artifactId>
			<version>${revision}</version>
		</dependency>
    </dependencies>
</project>