package dena.api.common.model.interop.context;

/**
 * Message types in DENA interoperability protocol.
 */
public enum DN00InteropMessageType {
	CLIENT_LOGIN_DEMO,
	CLIENT_LOGIN,
	CLIENT_REFRESH,
    CLIENT_SYNC_REQ,
    ADMIN_SYNC_PUSH,
    DENA_SYNC_PULL,
    CLIENT_RETRIEVE_REQ,
    CLIENT_PASSKEY_CLEAN_CREDENTIALS,
    CLIENT_PASSKEY_LOGIN_INIT,
    CLIENT_PASSKEY_LOGIN_FINISH,
    CLIENT_PASSKEY_REGISTER_INIT,
    CLIENT_PASSKEY_REGISTER_FINISH,

    CREATE_PULL_ADMIN_BESPOKE,
    GET_PULL_ADMIN_BESPOKE,
    FETCH_BESPOKE_EXPORT_ASSET,
    FETCH_PREGEN_EXPORT_ASSET,
    PERSON_ADMIN_SEARCH,
    PERSON_FETCH_DATA,
    PERSON_ADMIN_HEAD,
    ADMIN_SYNC_METADATA

}
